export default {
  GET_TOKEN: 'get-token',
  WRITE_TOKEN: 'write-token',
  GET_NAVBAR: 'get-navbar',
  GET_CATEGORY: 'get-category',
  GET_CATEGORY_RECOMMENDED: 'get-category-recommended',
  GET_ARTICLE: 'get-article',
  GET_HOME: 'get-home',
  GET_USER: 'get-user',
  UPDATE_USER: 'update-user',
  SAVE_BOOKMARK: 'save-bookmark',
  GET_BOOKMARKS: 'get-bookmarks',
  CLEAR_BOOKMARKS: 'clear-bookmarks',
  GET_BOOKS: 'get-books',
  CART_ADD: 'cart-add',
  CART_REMOVE: 'cart-remove',
  INC_QUANTITY: 'inc-quantity',
  DEC_QUANTITY: 'dec-quantity',
  SAVE_ORDER: 'save-order',
  CATEGORY_PARAMS: 'category-params',
  VERIFY_SEND: 'verify-send',
  VERIFY_PHONE: 'verify-phone',
  LOGIN: 'login',
  LOGOUT: 'logout',
  CLEAR_DATA: 'clear-data',
  FULFILLED: '_FULFILLED',
  REJECTED: '_REJECTED',
  PENDING: '_PENDING',
  SET_USER: 'SET_USER',
  UNAUTHORIZED: 'unauthorized',
  //

  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE'
};
